pipeline {
    agent any

    environment {
        REGISTRY = "brunoguidone/helloworldflask"
        REGISTRYID = "Dockerhub"
        DOCKERIMAGE = ""
    }

    options {
        timeout(time: 1, unit: 'HOURS')
    }

    stages{
        stage('Build & Tag Image') {
            steps {
                script{
                    DOCKERIMAGE = docker.build (registry + ":$BUILD_NUMBER", "-f ./deploy/Dockerfile .")
                }
            }
        }
        
        stage('Add image to kind') {
           steps {
               sh '''kind load docker-image $DOCKERIMAGE'''
           }
        }

        stage('Deploy Canary 10%') {
           steps {
               sh '''kubectl apply -f k8s-local-canary.yml'''
           }
        }

        stage('Annotate to 40%') {
           steps {
               sh '''kubectl annotate ingress helloworld-ingress nginx.ingress.kubernetes.io/canary-weight='40' -n coetech-canary --overwrite'''
           }
        }

        stage('Annotate to 100%') {
           steps {
               sh '''kubectl annotate ingress helloworld-ingress nginx.ingress.kubernetes.io/canary-weight='100' -n coetech-canary --overwrite'''
           }
        }

        stage('Deploy to Production') {
           steps {
               sh '''cat k8s-local-stable.yml | envsubst | kubectl apply -f -'''
           }
        }

        stage('Cleanup Canary') {
           steps {
               sh '''kubectl delete -f k8s-local-canary.yml'''
           }
        }
    }
}
