pipeline {
    agent any

    environment {
        REVISION = "${env.BUILD_NUMBER}"
        REGISTRY = "brunoguidone/helloworldflask"
        REGISTRYID = "Dockerhub"
        DOCKERIMAGE = ""
    }

    options {
        timeout(time: 1, unit: 'HOURS')
    }

    stages {
        //stage('Clone from github') {
        //    steps {
        //        git "https://github.com/brunoguidone/helloworldflask.git"
        //    }
        //}

        stage('Build & Tag Image') {
            steps {
                script{
                    DOCKERIMAGE = docker.build (registry + ":$BUILD_NUMBER", "-f ./deploy/Dockerfile .")
                }
            }
        }
        
        stage('Upload to Registry') {
            steps {
                script {
                    docker.withRegistry( '', REGISTRYID ) {
                        DOCKERIMAGE.push("$BUILD_NUMBER")
                        DOCKERIMAGE.push('latest')
                  }
               }
            }
        }

        stage('Cleaning images') {
            steps {
                sh '''docker rmi $registry:$BUILD_NUMBER'''
            }
        }

        //stage('Pulling and Deploying') {
        //    steps {
        //        sh '''docker pull
        //              docker run '''
        //    }
        //}
    }
}